### ISSUE TITLE
Having problem with loading exported weights

### ISSUE THREAD

**Issue by donmemedo** [KyanChen/BuildingExtraction#3]
Hi
when I ran my code:
```
model_infos = {
        # vgg16_bn, resnet50, resnet18
        'backbone': 'resnet50',
        'pretrained': True,
        'out_keys': ['block4'],
        'in_channel': 3,
        'n_classes': 2,
        'top_k_s': 64,
        'top_k_c': 16,
        'encoder_pos': True,
        'decoder_pos': True,
        'model_pattern': ['X', 'A', 'S', 'C'],
        'BATCH_SIZE': 6,
        'IS_SHUFFLE': True,
        'NUM_WORKERS': 10,
        'DATASET': 'Tools/generate_dep_info/train_data.csv',
        'model_path': '/mnt/STT/Checkpoints',
        'log_path': '/mnt/STT/Results',
        # if you need the validation process.
        'IS_VAL': True,
        'VAL_BATCH_SIZE': 1,
        'VAL_DATASET': 'Tools/generate_dep_info/val_data.csv',
        # if you need the test process.
        'IS_TEST': True,
        'TEST_DATASET': 'Tools/generate_dep_info/test_data.csv',
        'IMG_SIZE': [512, 512],
        'PHASE': 'seg',
        'PRIOR_MEAN': [0.6348953031, 0.5924549146, 0.5578144783],
        'PRIOR_STD': [0.02767351176, 0.02578138727, 0.02593547373]
    }
model = STTNet(**model_infos)
model.load_state_dict(torch.load('./ckpt_166.pt'))
.
.
.
 torch.save({
                'epoch_id': epoch_id,
                'model_state_dict': model.state_dict()
            }, os.path.join(model_infos['model_path'], f'ckpt_{epoch_id}.pt'))
```
that shows:

warning: num_class is not equal to 1000, which will cause some parameters to fail to load!
load resnet model...
Traceback (most recent call last):
  File "sahand2.py", line 179, in <module>
    main()
  File "sahand2.py", line 104, in main
    model.load_state_dict(torch.load(args.model))
  File "/home/mohammadamin.khataei/miniconda3/envs/STT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for STTNet:
	Missing key(s) in state_dict: "spatial_embedding_h", "spatial_embedding_w", "channel_embedding", "res_backbone.conv1.weight", "res_backbone.bn1.weight", "res_backbone.bn1.bias", "res_backbone.bn1.running_mean", "res_backbone.bn1.running_var", "res_backbone.layer1.0.conv1.weight", "res_backbone.layer1.0.bn1.weight", "res_backbone.layer1.0.bn1.bias", "res_backbone.layer1.0.bn1.running_mean", "res_backbone.layer1.0.bn1.running_var", "res_backbone.layer1.0.conv2.weight", "res_backbone.layer1.0.bn2.weight", "res_backbone.layer1.0.bn2.bias", "res_backbone.layer1.0.bn2.running_mean", "res_backbone.layer1.0.bn2.running_var", "res_backbone.layer1.0.conv3.weight", "res_backbone.layer1.0.bn3.weight", "res_backbone.layer1.0.bn3.bias", "res_backbone.layer1.0.bn3.running_mean", "res_backbone.layer1.0.bn3.running_var", "res_backbone.layer1.0.downsample.0.weight", "res_backbone.layer1.0.downsample.1.weight", "res_backbone.layer1.0.downsample.1.bias", "res_backbone.layer1.0.downsample.1.running_mean", "res_backbone.layer1.0.downsample.1.running_var", "res_backbone.layer1.1.conv1.weight", "res_backbone.layer1.1.bn1.weight", "res_backbone.layer1.1.bn1.bias", "res_backbone.layer1.1.bn1.running_mean", "res_backbone.layer1.1.bn1.running_var", "res_backbone.layer1.1.conv2.weight", "res_backbone.layer1.1.bn2.weight", "res_backbone.layer1.1.bn2.bias", "res_backbone.layer1.1.bn2.running_mean", "res_backbone.layer1.1.bn2.running_var", "res_backbone.layer1.1.conv3.weight", "res_backbone.layer1.1.bn3.weight", "res_backbone.layer1.1.bn3.bias", "res_backbone.layer1.1.bn3.running_mean", "res_backbone.layer1.1.bn3.running_var", "res_backbone.layer1.2.conv1.weight", "res_backbone.layer1.2.bn1.weight", "res_backbone.layer1.2.bn1.bias", "res_backbone.layer1.2.bn1.running_mean", "res_backbone.layer1.2.bn1.running_var", "res_backbone.layer1.2.conv2.weight", "res_backbone.layer1.2.bn2.weight", "res_backbone.layer1.2.bn2.bias", "res_backbone.layer1.2.bn2.running_mean", "res_backbone.layer1.2.bn2.running_var", "res_backbone.layer1.2.conv3.weight", "res_backbone.layer1.2.bn3.weight", "res_backbone.layer1.2.bn3.bias", "res_backbone.layer1.2.bn3.running_mean", "res_backbone.layer1.2.bn3.running_var", "res_backbone.layer2.0.conv1.weight", "res_backbone.layer2.0.bn1.weight", "res_backbone.layer2.0.bn1.bias", "res_backbone.layer2.0.bn1.running_mean", "res_backbone.layer2.0.bn1.running_var", "res_backbone.layer2.0.conv2.weight", "res_backbone.layer2.0.bn2.weight", "res_backbone.layer2.0.bn2.bias", "res_backbone.layer2.0.bn2.running_mean", "res_backbone.layer2.0.bn2.running_var", "res_backbone.layer2.0.conv3.weight", "res_backbone.layer2.0.bn3.weight", "res_backbone.layer2.0.bn3.bias", "res_backbone.layer2.0.bn3.running_mean", "res_backbone.layer2.0.bn3.running_var", "res_backbone.layer2.0.downsample.0.weight", "res_backbone.layer2.0.downsample.1.weight", "res_backbone.layer2.0.downsample.1.bias", "res_backbone.layer2.0.downsample.1.running_mean", "res_backbone.layer2.0.downsample.1.running_var", "res_backbone.layer2.1.conv1.weight", "res_backbone.layer2.1.bn1.weight", "res_backbone.layer2.1.bn1.bias", "res_backbone.layer2.1.bn1.running_mean", "res_backbone.layer2.1.bn1.running_var", "res_backbone.layer2.1.conv2.weight", "res_backbone.layer2.1.bn2.weight", "res_backbone.layer2.1.bn2.bias", "res_backbone.layer2.1.bn2.running_mean", "res_backbone.layer2.1.bn2.running_var", "res_backbone.layer2.1.conv3.weight", "res_backbone.layer2.1.bn3.weight", "res_backbone.layer2.1.bn3.bias", "res_backbone.layer2.1.bn3.running_mean", "res_backbone.layer2.1.bn3.running_var", "res_backbone.layer2.2.conv1.weight", "res_backbone.layer2.2.bn1.weight", "res_backbone.layer2.2.bn1.bias", "res_backbone.layer2.2.bn1.running_mean", "res_backbone.layer2.2.bn1.running_var", "res_backbone.layer2.2.conv2.weight", "res_backbone.layer2.2.bn2.weight", "res_backbone.layer2.2.bn2.bias", "res_backbone.layer2.2.bn2.running_mean", "res_backbone.layer2.2.bn2.running_var", "res_backbone.layer2.2.conv3.weight", "res_backbone.layer2.2.bn3.weight", "res_backbone.layer2.2.bn3.bias", "res_backbone.layer2.2.bn3.running_mean", "res_backbone.layer2.2.bn3.running_var", "res_backbone.layer2.3.conv1.weight", "res_backbone.layer2.3.bn1.weight", "res_backbone.layer2.3.bn1.bias", "res_backbone.layer2.3.bn1.running_mean", "res_backbone.layer2.3.bn1.running_var", "res_backbone.layer2.3.conv2.weight", "res_backbone.layer2.3.bn2.weight", "res_backbone.layer2.3.bn2.bias", "res_backbone.layer2.3.bn2.running_mean", "res_backbone.layer2.3.bn2.running_var", "res_backbone.layer2.3.conv3.weight", "res_backbone.layer2.3.bn3.weight", "res_backbone.layer2.3.bn3.bias", "res_backbone.layer2.3.bn3.running_mean", "res_backbone.layer2.3.bn3.running_var", "res_backbone.layer3.0.conv1.weight", "res_backbone.layer3.0.bn1.weight", "res_backbone.layer3.0.bn1.bias", "res_backbone.layer3.0.bn1.running_mean", "res_backbone.layer3.0.bn1.running_var", "res_backbone.layer3.0.conv2.weight", "res_backbone.layer3.0.bn2.weight", "res_backbone.layer3.0.bn2.bias", "res_backbone.layer3.0.bn2.running_mean", "res_backbone.layer3.0.bn2.running_var", "res_backbone.layer3.0.conv3.weight", "res_backbone.layer3.0.bn3.weight", "res_backbone.layer3.0.bn3.bias", "res_backbone.layer3.0.bn3.running_mean", "res_backbone.layer3.0.bn3.running_var", "res_backbone.layer3.0.downsample.0.weight", "res_backbone.layer3.0.downsample.1.weight", "res_backbone.layer3.0.downsample.1.bias", "res_backbone.layer3.0.downsample.1.running_mean", "res_backbone.layer3.0.downsample.1.running_var", "res_backbone.layer3.1.conv1.weight", "res_backbone.layer3.1.bn1.weight", "res_backbone.layer3.1.bn1.bias", "res_backbone.layer3.1.bn1.running_mean", "res_backbone.layer3.1.bn1.running_var", "res_backbone.layer3.1.conv2.weight", "res_backbone.layer3.1.bn2.weight", "res_backbone.layer3.1.bn2.bias", "res_backbone.layer3.1.bn2.running_mean", "res_backbone.layer3.1.bn2.running_var", "res_backbone.layer3.1.conv3.weight", "res_backbone.layer3.1.bn3.weight", "res_backbone.layer3.1.bn3.bias", "res_backbone.layer3.1.bn3.running_mean", "res_backbone.layer3.1.bn3.running_var", "res_backbone.layer3.2.conv1.weight", "res_backbone.layer3.2.bn1.weight", "res_backbone.layer3.2.bn1.bias", "res_backbone.layer3.2.bn1.running_mean", "res_backbone.layer3.2.bn1.running_var", "res_backbone.layer3.2.conv2.weight", "res_backbone.layer3.2.bn2.weight", "res_backbone.layer3.2.bn2.bias", "res_backbone.layer3.2.bn2.running_mean", "res_backbone.layer3.2.bn2.running_var", "res_backbone.layer3.2.conv3.weight", "res_backbone.layer3.2.bn3.weight", "res_backbone.layer3.2.bn3.bias", "res_backbone.layer3.2.bn3.running_mean", "res_backbone.layer3.2.bn3.running_var", "res_backbone.layer3.3.conv1.weight", "res_backbone.layer3.3.bn1.weight", "res_backbone.layer3.3.bn1.bias", "res_backbone.layer3.3.bn1.running_mean", "res_backbone.layer3.3.bn1.running_var", "res_backbone.layer3.3.conv2.weight", "res_backbone.layer3.3.bn2.weight", "res_backbone.layer3.3.bn2.bias", "res_backbone.layer3.3.bn2.running_mean", "res_backbone.layer3.3.bn2.running_var", "res_backbone.layer3.3.conv3.weight", "res_backbone.layer3.3.bn3.weight", "res_backbone.layer3.3.bn3.bias", "res_backbone.layer3.3.bn3.running_mean", "res_backbone.layer3.3.bn3.running_var", "res_backbone.layer3.4.conv1.weight", "res_backbone.layer3.4.bn1.weight", "res_backbone.layer3.4.bn1.bias", "res_backbone.layer3.4.bn1.running_mean", "res_backbone.layer3.4.bn1.running_var", "res_backbone.layer3.4.conv2.weight", "res_backbone.layer3.4.bn2.weight", "res_backbone.layer3.4.bn2.bias", "res_backbone.layer3.4.bn2.running_mean", "res_backbone.layer3.4.bn2.running_var", "res_backbone.layer3.4.conv3.weight", "res_backbone.layer3.4.bn3.weight", "res_backbone.layer3.4.bn3.bias", "res_backbone.layer3.4.bn3.running_mean", "res_backbone.layer3.4.bn3.running_var", "res_backbone.layer3.5.conv1.weight", "res_backbone.layer3.5.bn1.weight", "res_backbone.layer3.5.bn1.bias", "res_backbone.layer3.5.bn1.running_mean", "res_backbone.layer3.5.bn1.running_var", "res_backbone.layer3.5.conv2.weight", "res_backbone.layer3.5.bn2.weight", "res_backbone.layer3.5.bn2.bias", "res_backbone.layer3.5.bn2.running_mean", "res_backbone.layer3.5.bn2.running_var", "res_backbone.layer3.5.conv3.weight", "res_backbone.layer3.5.bn3.weight", "res_backbone.layer3.5.bn3.bias", "res_backbone.layer3.5.bn3.running_mean", "res_backbone.layer3.5.bn3.running_var", "reduce_channel_b5.0.weight", "reduce_channel_b5.0.bias", "reduce_channel_b5.1.weight", "reduce_channel_b5.1.bias", "reduce_channel_b5.1.running_mean", "reduce_channel_b5.1.running_var", "get_s_probability.0.weight", "get_s_probability.0.bias", "get_s_probability.1.weight", "get_s_probability.1.bias", "get_s_probability.1.running_mean", "get_s_probability.1.running_var", "get_s_probability.3.weight", "get_s_probability.3.bias", "tf_encoder_spatial_b5.weights_qkv.0.weight", "tf_encoder_spatial_b5.weights_qkv.1.weight", "tf_encoder_spatial_b5.weights_qkv.2.weight", "tf_encoder_spatial_b5.out_layer.0.weight", "tf_encoder_spatial_b5.out_layer.0.bias", "tf_encoder_spatial_b5.layer_norm.weight", "tf_encoder_spatial_b5.layer_norm.bias", "tf_decoder_spatial_b5.weights_qkv.0.weight", "tf_decoder_spatial_b5.weights_qkv.1.weight", "tf_decoder_spatial_b5.weights_qkv.2.weight", "tf_decoder_spatial_b5.out_layer.0.weight", "tf_decoder_spatial_b5.out_layer.0.bias", "tf_decoder_spatial_b5.layer_norm.weight", "tf_decoder_spatial_b5.layer_norm.bias", "get_c_probability.0.weight", "get_c_probability.0.bias", "get_c_probability.1.weight", "get_c_probability.1.bias", "get_c_probability.1.running_mean", "get_c_probability.1.running_var", "get_c_probability.3.weight", "get_c_probability.3.bias", "tf_encoder_channel_b5.weights_qkv.0.weight", "tf_encoder_channel_b5.weights_qkv.1.weight", "tf_encoder_channel_b5.weights_qkv.2.weight", "tf_encoder_channel_b5.out_layer.0.weight", "tf_encoder_channel_b5.out_layer.0.bias", "tf_encoder_channel_b5.layer_norm.weight", "tf_encoder_channel_b5.layer_norm.bias", "tf_decoder_channel_b5.weights_qkv.0.weight", "tf_decoder_channel_b5.weights_qkv.1.weight", "tf_decoder_channel_b5.weights_qkv.2.weight", "tf_decoder_channel_b5.out_layer.0.weight", "tf_decoder_channel_b5.out_layer.0.bias", "tf_decoder_channel_b5.layer_norm.weight", "tf_decoder_channel_b5.layer_norm.bias", "before_predict_head_conv.0.weight", "before_predict_head_conv.0.bias", "before_predict_head_conv.1.weight", "before_predict_head_conv.1.bias", "before_predict_head_conv.1.running_mean", "before_predict_head_conv.1.running_var", "double_conv1.double_conv.0.weight", "double_conv1.double_conv.0.bias", "double_conv1.double_conv.1.weight", "double_conv1.double_conv.1.bias", "double_conv1.double_conv.1.running_mean", "double_conv1.double_conv.1.running_var", "double_conv1.double_conv.3.weight", "double_conv1.double_conv.3.bias", "double_conv1.double_conv.4.weight", "double_conv1.double_conv.4.bias", "double_conv1.double_conv.4.running_mean", "double_conv1.double_conv.4.running_var", "double_conv2.double_conv.0.weight", "double_conv2.double_conv.0.bias", "double_conv2.double_conv.1.weight", "double_conv2.double_conv.1.bias", "double_conv2.double_conv.1.running_mean", "double_conv2.double_conv.1.running_var", "double_conv2.double_conv.3.weight", "double_conv2.double_conv.3.bias", "double_conv2.double_conv.4.weight", "double_conv2.double_conv.4.bias", "double_conv2.double_conv.4.running_mean", "double_conv2.double_conv.4.running_var", "predict_head_out.0.weight", "predict_head_out.0.bias", "predict_head_out.1.weight", "predict_head_out.1.bias", "predict_head_out.1.running_mean", "predict_head_out.1.running_var", "predict_head_out.3.weight", "predict_head_out.3.bias", "loss_att_branch.0.weight", "loss_att_branch.0.bias", "loss_att_branch.1.weight", "loss_att_branch.1.bias", "loss_att_branch.1.running_mean", "loss_att_branch.1.running_var", "loss_att_branch.3.weight", "loss_att_branch.3.bias". 
	Unexpected key(s) in state_dict: "epoch_id", "model_state_dict". 

why this error happened and how i can handle it?

**Comment by KyanChen** [comment]
We have updated the code!
epoch_start = 0
    if os.path.exists(model_infos['load_checkpoint_path']):
        print(f'load checkpoint from {model_infos["load_checkpoint_path"]}')
        state_dict = torch.load(model_infos['load_checkpoint_path'], map_location='cpu')
        epoch_start = state_dict['epoch_id']
        model_dict = state_dict['model_state_dict']
        model.load_state_dict(model_dict)

**Comment by donmemedo** [comment]
thanks for your fast reply <3
