### ISSUE TITLE
能分享一下训练好的模型吗？

### ISSUE THREAD

**Issue by dongshaojia** [KyanChen/BuildingExtraction#4]
感谢您的工作，我的资源有限，训练出来很难，能分享一下您训练好的模型吗？感谢！

**Comment by KyanChen** [comment]
可以的，稍后给出！

**Comment by KyanChen** [comment]
已上传至https://huggingface.co/KyanChen/BuildingExtraction/tree/main/Pretrain

**Comment by dongshaojia** [comment]
非常感谢！
