### ISSUE TITLE
请求

### ISSUE THREAD

**Issue by YUHsss** [KyanChen/BuildingExtraction#7]
作者您好，请问方便提供一下论文中生成概率图的代码吗？

**Comment by KyanChen** [comment]
[已提供参考代码，需要自己细微调整，[show_feature](https://github.com/KyanChen/BuildingExtraction/blob/main/Utils/Utils.py)

**Comment by YUHsss** [comment]
非常感谢，我刚才到了这段代码，但是我有个疑问就是f_tensor需要传入什么吗还是自行指定，label是自己预测的结果标签还是真实标签呢？ 谢谢！

**Comment by KyanChen** [comment]
f_tensor是中间的特征图，label和img可以不传入

**Comment by ChenHongyu-bo** [comment]
好的，谢谢您

**Comment by YUHsss** [comment]
> f_tensor是中间的特征图，label和img可以不传入

我刚才在可视化的时候它抛出了这个错误，我将网络最后一层的特征图提取出来，网络最后输出为1x256x256
`ValueError: Must pass 2-d input. shape=(1, 256, 256)`

我的代码是这样的，您能帮我检查一下吗？
```
    trans = torchvision.transforms.Compose([torchvision.transforms.ToTensor(), ])
    img = cv2.imread(r"F:\ww\dataset\pre/2_0_3.tif")

    img = trans(img).unsqueeze(0)

    model = Net()
    model.eval()
    conv_img = model(img)  # conv_img 卷积结果
    conv_img = conv_img[0]
    conv_img = conv_img.squeeze(0)

    print(conv_img)

    show_feature(conv_img,None,None)
```

**Comment by KyanChen** [comment]
你没训练好吧，可以把predict label也输出看看

**Comment by YUHsss** [comment]
![image](https://user-images.githubusercontent.com/108503577/177527626-6c96725e-4db2-435b-8e12-d2d749141d93.png)
这是predict的

**Comment by YUHsss** [comment]
不好意思，是我的问题，我加载模型加载错了

**Comment by ChenHongyu-bo** [comment]
刚才我试了试将is_channel=True 发现运行的时间好长一直没出结果，请问这是我的问题吗？

**Comment by YUHsss** [comment]
刚才我试了试将is_channel = True ，发现运行时间好长，一直没出结果，请问这是我的问题吗还是就是需要等待很久？

**Comment by KyanChen** [comment]
用调试模式看看吧

**Comment by YUHsss** [comment]
请问如果我想输出通道数为64的特征图，这种情况不能squeeze了，需要修改哪里呢？
`ValueError: Must pass 2-d input. shape=(64, 512, 512)`
